import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import client from "client";
import { gql } from "@apollo/client";
import { BlockRenderer } from "@/components/BlockRenderer";
import {
  cleanAndTransformBlocks,
  Blocks,
} from "@/utils/cleanAndTransformBlocks";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
  blocks: Blocks;
}

const Home: React.FC<HomeProps> = ({ blocks, mainMenuItems }) => {
  console.log(blocks, mainMenuItems);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BlockRenderer blocks={blocks} />
      </main>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const { data } = await client.query({
    query: gql`
      query PageQuery {
        nodeByUri(uri: "/") {
          ... on Page {
            id
            blocks
          }
        }
        acfOptionsMainMenu {
          mainMenu {
            menuItems {
              items {
                destination {
                  ... on Page {
                    uri
                  }
                }
                label
              }
              menuItem {
                destination {
                  ... on Page {
                    uri
                  }
                }
                label
              }
            }
          }
        }
      }
    `,
  });

  console.log("query", data.acfOptionsMainMenu.mainMenu.menuItems);

  return {
    props: {
      mainMenuItems: data.acfOptionsMainMenu.mainMenu.menuItems,
      blocks: cleanAndTransformBlocks(data.nodeByUri.blocks),
    },
  };
};
