import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { BlockRenderer } from "@/components/BlockRenderer";
import { Blocks } from "@/utils/cleanAndTransformBlocks";
import { MainMenu } from "@/components/MainMenu";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
  blocks: Blocks;
  mainMenuItems: any;
  callToActionLabel: string;
  callToActionDestination: string;
}

export const Page: React.FC<HomeProps> = ({
  blocks,
  mainMenuItems,
  callToActionLabel,
  callToActionDestination,
}) => {
  return (
    <>
      <Head>
        <title>The Unfixed Mind</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MainMenu
          mainMenuItems={mainMenuItems}
          callToActionLabel={callToActionLabel}
          callToActionDestination={callToActionDestination}
        />
        <BlockRenderer blocks={blocks} />
      </main>
    </>
  );
};
